name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  actionlint:
    name: Lint Workflows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: actionlint
        uses: raven-actions/actionlint@v2

  python:
    name: Python
    uses: ./.github/workflows/python-ci.yml
